origins:
  -  rules:
      - path: /wp-login.php
      - path: /api/compute/compute
        method: POST
        default: s-maxage=600
      - default: s-maxage=600
        override: s-maxage=3600
        headers:
          Vary: Accept-Encoding
