port: 8080
provider: memory
origins:
  # - origin: https://ericselin.dev
  #   host: esdev.localhost
  #   # ten minute default ttl
  #   defaultCacheControl: s-maxage=600
  - origin: https://www.arktis3d.com
    host: arktis3d.localhost
    disableUpdate: true
    paths:
      - prefix: /api/
        defaults:
          safeMethods:
            - POST
          # 12h default ttl
          cacheControl: s-maxage=43200